(part "BT139-600E_127"
    (packageRef "TO254P470X1000X2000-3P")
    (interface
        (port "1" (symbPinId 1) (portName "MT1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MT2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "G") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "771-BT139-600E127")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/WeEn-Semiconductors/BT139-600E127?qs=me8TqzrmIYU78FBWg3nQmw%3D%3D")
    (property "Manufacturer_Name" "WeEn Semiconductors")
    (property "Manufacturer_Part_Number" "BT139-600E,127")
    (property "Description" "Triacs RAIL TRIAC")
    (property "Datasheet_Link" "")
    (property "symbolName1" "BT139-600E_127")
)
