(part "MOC3021SM"
    (packageRef "SOP254P916X480-6N")
    (interface
        (port "1" (symbPinId 1) (portName "ANODE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CATHODE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "N/C") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MAIN_TERM._1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC") (portType INOUT))
        (port "6" (symbPinId 6) (portName "MAIN_TERM._2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "512-MOC3021SM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/MOC3021SM?qs=ZS9em9a1DI4mnS4oQ%2FdKAA%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MOC3021SM")
    (property "Description" "6-Pin DIP Random-Phase Triac Driver Output Optocoupler (250/400 V Peak)")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/MOC3023M-D.PDF")
    (property "symbolName1" "MOC3021SM")
)
