(part "MOC3061SR2M"
    (packageRef "SOT254P916X508-6N")
    (interface
        (port "1" (symbPinId 1) (portName "ANODE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CATHODE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "N/C") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MAIN_TERM._1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC") (portType INOUT))
        (port "6" (symbPinId 6) (portName "MAIN_TERM._2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "512-MOC3061SR2M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/MOC3061SR2M?qs=QsyUFYHC2%2FbVF%2F%252BX5tJ1cA%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MOC3061SR2M")
    (property "Description" "Triac & SCR Output Optocouplers 6Pin600V Optocoupler Zero Cross Triac Dr")
    (property "Datasheet_Link" "http://www.onsemi.com/pub/Collateral/MOC3163M-D.pdf")
    (property "symbolName1" "MOC3061SR2M")
)
