(part "CPC1966Y"
    (packageRef "CPC1966Y")
    (interface
        (port "1" (symbPinId 1) (portName "-LED") (portType INOUT))
        (port "2" (symbPinId 2) (portName "+LED") (portType INOUT))
        (port "3" (symbPinId 3) (portName "AC_LOAD_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "AC_LOAD_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "161")
    (property "Mouser_Part_Number" "849-CPC1966Y")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/IXYS-Integrated-Circuits/CPC1966Y?qs=8uBHJDVwVqxNfAOiNv29Iw%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "CPC1966Y")
    (property "Description" "IXYS 3 A rms SPNO Solid State Relay, Zero Crossing, PCB Mount SCR, 240 V ac Maximum Load")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/4bd38bcd53ac06cbf93d43ee226943fd.pdf")
    (property "symbolName1" "CPC1966Y")
)
