(part "B3F-4055S"
    (packageRef "B3F4055S")
    (interface
        (port "1" (symbPinId 1) (portName "COM_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "653-B3F-4055S")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/B3F-4055S?qs=nUVjeaT6QSw5AU9Uc2mCbQ%3D%3D")
    (property "Manufacturer_Name" "Omron Electronics")
    (property "Manufacturer_Part_Number" "B3F-4055S")
    (property "Description" "Tactile Switches 12X12 PROJ 7.3MM BTN TACTILE")
    (property "Datasheet_Link" "https://media.digikey.com/pdf/Data%20Sheets/Omron%20PDFs/B3F.pdf")
    (property "symbolName1" "B3F-4055S")
)
