(part "IRM-02-3_3"
    (packageRef "IRM-02_PCB-MOUNTING_")
    (interface
        (port "1" (symbPinId 1) (portName "-V") (portType INOUT))
        (port "2" (symbPinId 2) (portName "AC/N") (portType INOUT))
        (port "3" (symbPinId 3) (portName "AC/L") (portType INOUT))
        (port "4" (symbPinId 4) (portName "+V") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "709-IRM02-3.3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/MEAN-WELL/IRM-02-3.3?qs=C9r8PV%2F%252BoWOqS8sbyxobNQ%3D%3D")
    (property "Manufacturer_Name" "Mean Well")
    (property "Manufacturer_Part_Number" "IRM-02-3.3")
    (property "Description" "Power Supply Encapsulated PCB 3.3V 2W")
    (property "Datasheet_Link" "http://www.meanwell.com/Upload/PDF/IRM-02/IRM-02-SPEC.PDF")
    (property "symbolName1" "IRM-02-3_3")
)
