(part "BTA10-600BWRG"
    (packageRef "TO255P460X1020X2005-3P")
    (interface
        (port "1" (symbPinId 1) (portName "MT1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MT2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "G") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-BTA10-600BW")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/BTA10-600BWRG?qs=%2Fa2FmOVcLL9HVUO2jWvyeg%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "BTA10-600BWRG")
    (property "Description" "TRIAC Alternistor - Snubberless 600 V 10 A Through Hole TO-220")
    (property "Datasheet_Link" "http://www.st.com/web/en/resource/technical/document/datasheet/CD00004894.pdf")
    (property "symbolName1" "BTA10-600BWRG")
)
